### ISSUE TITLE
Error when trying to configure

### ISSUE THREAD

**Issue by fg6** [schloi/MARVEL#1]
Hi,
I am trying to install MARVEL but I encounter a problem during the configuration step. 
I cloned the repo with git clone and then ran the configuration step as:
  $ configure --prefix=/software/hpag/MARVEL
but it crashes with error:
  config.status: error: cannot find input file: `config.h.in'
The full output is in attachment. Can you please help me understanding what is wrong? 
Please let me know if you need some more information.

Thank you!
Fran
[error.txt](https://github.com/schloi/MARVEL/files/1450849/error.txt)

**Comment by schloi** [comment]
I removed the configure script from the repo, since it shouldn't have been included there in the first place. You need to run autoreconf, that will generate a proper configure script and the missing config.h.in.
