### ISSUE TITLE
is GTK3 a hard requirement for full MARVEL compilation, or can it work with GTK2?

### ISSUE THREAD

**Issue by SchwarzEM** [schloi/MARVEL#10]
I am trying to compile MARVEL and unable to do so fully, perhaps because both of the Linux machines to which I have access use GTK 2.0, not GTK 3.0.  When I run the command:

    cd /home/schwarz/src/MARVEL ;
    autoreconf ;
    ./configure --prefix=/home/schwarz/src/MARVEL ;

 I get the following error messages:

"""
checking for GTK... no
[...]
--------------------------------
 gtk not found
 skipping apps depending on it
--------------------------------
"""

Is GTK 3.0 a hard requirement to run MARVEL, or can it work with GTK 2.0?  Are there extra commands that I should be running to get MARVEL to 'see' GTK?

**Comment by schloi** [comment]
I only targeted GTK3+ during the development. That said, the build will only skip LAexplorer in case you are missing GTK, which is not essential. LAexplorer allows you to visually inspect the alignments and I mostly use it during development and to fine-tune the arguments the various tools take.

**Comment by SchwarzEM** [comment]
OK; thanks!  That is very reassuring to know.  It means that I should have MARVEL effectively completely compiled for all real purposes.
