### ISSUE TITLE
Why does do.py (test script, in examples/e.coli_pacbio) not run to completion?

### ISSUE THREAD

**Issue by SchwarzEM** [schloi/MARVEL#11]
I have installed MARVEL and tried running it on a test data set.  The test starts to work, but then fails.  Here are the commands I've run, with a few key responses.

    cd /home/schwarz/src ;
    git clone https://github.com/schloi/MARVEL.git MARVEL_13feb2018 ;
    cd MARVEL_13feb2018 ;
    autoreconf ;
    ./configure --prefix=/home/schwarz/src/MARVEL_13feb2018 ;

checking for GTK... no
gtk not found
skipping apps depending on it

    # keep going
    make ;
    make install ;

Installation into /home/schwarz/src/MARVEL_13feb2018 finished.
Don't forget to include /home/schwarz/src/MARVEL_13feb2018/lib.python in your PYTHONPATH.

    # do that, then!
    PYTHONPATH="/home/schwarz/src/MARVEL_13feb2018/lib.python:$PYTHONPATH" ;
    export PYTHONPATH ;

    # Now, let us see if an instance in MARVEL can work.
    cd examples/e.coli_pacbio ;

    gunzip p6.25x.fasta.gz ;    

    /home/schwarz/src/MARVEL_13feb2018/scripts/DBprepare.py ECOL p6.25x.fasta ;

-bash: /home/schwarz/src/MARVEL_13feb2018/scripts/DBprepare.py: Permission denied

    # whoops! why did that happen? check the permissions:
    ls -l /home/schwarz/src/MARVEL_13feb2018/scripts/*.py ;

-rwxr-xr-x 1 schwarz schwarz  5880 Feb 13 14:06 /home/schwarz/src/MARVEL_13feb2018/scripts/colormap.py
-rwxr-xr-x 1 schwarz schwarz   443 Feb 13 14:06 /home/schwarz/src/MARVEL_13feb2018/scripts/constants.py
-rw-r--r-- 1 schwarz schwarz  5930 Feb 13 13:32 /home/schwarz/src/MARVEL_13feb2018/scripts/DBprepare.py
-rwxr-xr-x 1 schwarz schwarz 32897 Feb 13 14:06 /home/schwarz/src/MARVEL_13feb2018/scripts/OGtour.py
-rw-r--r-- 1 schwarz schwarz  1456 Feb 13 13:32 /home/schwarz/src/MARVEL_13feb2018/scripts/paths2rids.py
-rw-r--r-- 1 schwarz schwarz   607 Feb 13 13:32 /home/schwarz/src/MARVEL_13feb2018/scripts/rid2bid.py
-rwxr-xr-x 1 schwarz schwarz 12228 Feb 13 14:06 /home/schwarz/src/MARVEL_13feb2018/scripts/tour2fasta.py

    # set the permissions consistently right
    chmod 755 /home/schwarz/src/MARVEL_13feb2018/scripts/*.py ;

    # now try again, and get more promising results
    /home/schwarz/src/MARVEL_13feb2018/scripts/DBprepare.py ECOL p6.25x.fasta ;

converting fasta to db ( min read length 2000 )
partitioning db ( blocksize 200 )
dusting db
creating plan

    ls -lt ;

-rw-r--r-- 1 schwarz schwarz        47 Feb 13 14:12 ECOL.merge.plan
-rw-r--r-- 1 schwarz schwarz        48 Feb 13 14:12 ECOL.dalign.plan
-rw-r--r-- 1 schwarz schwarz       158 Feb 13 14:12 ECOL.db
-rw-r--r-- 1 schwarz schwarz 117327942 Feb 13 13:29 p6.25x.fasta
-rwxr-xr-x 1 schwarz schwarz      4398 Feb 13 13:29 do.py
-rw-r--r-- 1 schwarz schwarz        98 Feb 13 13:29 README

    cp -ip do.py orig_do.py_file ;

    # We're going to need to point this thing at Python3 explicitly
    # also, set a hard limit of 8 CPUs
    pico do.py ;

    diff orig_do.py_file do.py ;

> 1c1
< #!/usr/bin/env python
---
> #!/usr/bin/env python3
14c14
< PARALLEL   = multiprocessing.cpu_count()
---
> PARALLEL   = 8

    # So, now see if this can work, or if it fails, and if so, where.
    ./do.py ;

[1 8] /home/schwarz/src/MARVEL_13feb2018/bin/daligner -v -I -t20 -e0.7 -r1 -j4 ECOL.1 ECOL.1
[2 8] /home/schwarz/src/MARVEL_13feb2018/bin/LAmerge -v -n 8 ECOL.db ECOL.1.las d001_00001
[3 8] /home/schwarz/src/MARVEL_13feb2018/bin/LAq -b 1 ECOL ECOL.1.las
[4 8] /home/schwarz/src/MARVEL_13feb2018/bin/TKmerge -d ECOL q
[5 8] /home/schwarz/src/MARVEL_13feb2018/bin/TKmerge -d ECOL trim
[6 8] /home/schwarz/src/MARVEL_13feb2018/bin/LAfix -g -1 ECOL ECOL.1.las ECOL.1.fixed.fasta
[7 8] !cat ECOL.*.fixed.fasta > ECOL.fixed.fasta
[8 8] /home/schwarz/src/MARVEL_13feb2018/scripts/DBprepare.py -s 50 -r 2 -j 4 -g 4600000 ECOL_FIX ECOL.fixed.fasta
Traceback (most recent call last):
  File "./do.py", line 44, in <module>
    q = marvel.queue.queue(DB_FIX, COVERAGE, PARALLEL)
  File "/home/schwarz/src/MARVEL_13feb2018/lib.python/marvel/queue.py", line 40, in __init__
    for strLine in open(self.db + ".db"):
FileNotFoundError: [Errno 2] No such file or directory: 'ECOL_FIX.db'

    # so, it started to work, then blew up! what files do I find myself with?
    ls -lt ;

-rw-r--r-- 1 schwarz schwarz         0 Feb 13 14:19 ECOL_FIX.merge.plan
-rw-r--r-- 1 schwarz schwarz         0 Feb 13 14:19 ECOL_FIX.dalign.plan
-rw-r--r-- 1 schwarz schwarz        18 Feb 13 14:19 ECOL_FIX.dbx
-rw-r--r-- 1 schwarz schwarz 112043351 Feb 13 14:19 ECOL.fixed.fasta
-rw-r--r-- 1 schwarz schwarz 112043351 Feb 13 14:19 ECOL.1.fixed.fasta
-rw-r--r-- 1 schwarz schwarz  75965172 Feb 13 14:19 ECOL.1.las
drwxr-xr-x 2 schwarz schwarz        38 Feb 13 14:19 d001_00001
-rwxr-xr-x 1 schwarz schwarz      4373 Feb 13 14:16 do.py
-rw-r--r-- 1 schwarz schwarz        47 Feb 13 14:12 ECOL.merge.plan
-rw-r--r-- 1 schwarz schwarz        48 Feb 13 14:12 ECOL.dalign.plan
-rw-r--r-- 1 schwarz schwarz       158 Feb 13 14:12 ECOL.db
-rw-r--r-- 1 schwarz schwarz 117327942 Feb 13 13:29 p6.25x.fasta
-rwxr-xr-x 1 schwarz schwarz      4398 Feb 13 13:29 orig_do.py_file
-rw-r--r-- 1 schwarz schwarz        98 Feb 13 13:29 README

Why did this fail?

**Comment by schloi** [comment]
DBprepare, or rather FA2db (which is called by DBprepare) failed. You can tell by the presence of the .dbx file, which gets renamed to .db when FA2db has done its work. Obviously there is still lots and lots of room for proper error handling all over the place. sorry about that.

anyway, get rid of ECOL_FIX.* and .ECOL_FIX* and try running
`/home/schwarz/src/MARVEL_13feb2018/scripts/DBprepare.py -s 50 -r 2 -j 4 -g 4600000 ECOL_FIX ECOL.fixed.fasta`
from the command line. hopefully it spits out some meaningful error messages.

**Comment by SchwarzEM** [comment]
I've run the following commands, and gotten the following results:

cd /home/schwarz/src/MARVEL_13feb2018/examples/e.coli_pacbio ;

PYTHONPATH="/home/schwarz/src/MARVEL_13feb2018/lib.python:$PYTHONPATH" ;
export PYTHONPATH ;

rm ECOL_FIX* .ECOL_FIX* ;

/home/schwarz/src/MARVEL_13feb2018/scripts/DBprepare.py -s 50 -r 2 -j 4 -g 4600000 ECOL_FIX ECOL.fixed.fasta 1>test.out 2>test.err ;

more test.out ;

converting fasta to db ( min read length 2000 )
partitioning db ( blocksize 50 )
dusting db
creating plan

more test.err ;

malformed track name: '˝gıÏsyïöÌëQ°á˘mﬂ–ÔÆ<Q≈4¨2íìtÉﬁfaBRñRo•¥Üd$ö<Re&eÏ3õjŸÈ
»9pel	/—dù,i'
(null): Could not open database ECOL_FIX
[ERROR] Cannot open database ECOL_FIX
(null): Could not open database ECOL_FIX
failed to open database

ls -lat | head ;

total 437436
-rw-r--r-- 1 schwarz schwarz       106 Feb 14 11:42 test.out
-rw-r--r-- 1 schwarz schwarz       250 Feb 14 11:42 test.err
drwxr-xr-x 3 schwarz schwarz      4096 Feb 14 11:42 .
-rw-r--r-- 1 schwarz schwarz         0 Feb 14 11:42 ECOL_FIX.merge.plan
-rw-r--r-- 1 schwarz schwarz         0 Feb 14 11:42 ECOL_FIX.dalign.plan
-rw-r--r-- 1 schwarz schwarz        18 Feb 14 11:42 ECOL_FIX.dbx
-rw-r--r-- 1 schwarz schwarz       120 Feb 14 11:42 .ECOL_FIX.idx
-rw-r--r-- 1 schwarz schwarz      1521 Feb 14 11:42 .ECOL_FIX.bps
-rw-r--r-- 1 schwarz schwarz 112043351 Feb 13 14:19 ECOL.fixed.fasta

... so, there are error messages, but I am not sure what they mean or what to do about them!

**Comment by schloi** [comment]
I checked in a bunch of fixes which also address your problem. Note that the example driver script (the do.py) has been changed as well.

**Comment by SchwarzEM** [comment]
Those fixes worked!  I was able to compile MARVEL and run it successfully on the test data in MARVEL/examples/e.coli_pacbio.  Thank you for your prompt help.
