### ISSUE TITLE
Example Ecoli pacbio - tour2fasta do not run

### ISSUE THREAD

**Issue by sguizard** [schloi/MARVEL#12]
Hi, 

I'm trying to run MARVEL on the example files of pacbio e coli. 
After apllying the workaround given in the issue #9, (remove the -c option of FA2DB command in DBprepare.py) I'm able to run the setup step. 
Before running do.py, I correct the step 15 by also removing the -c option from the FA2DB command.
When I run the do.py script, everything run fine until the tour2fasta step where the script stop without any errors messages. 

So I copy paste the last command, run it and got the following error message.

```
/opt/MARVEL/scripts/tour2fasta.py -c ECOL_FIX_CORRECTED -t trim1 ECOL_FIX ECOL_FIX.tour.graphml ECOL_FIX.tour.paths
opening db ECOL_FIX
opening corrected db ECOL_FIX_CORRECTED
loading graph ECOL_FIX.tour.graphml
mapping read ids
Traceback (most recent call last):
  File "/opt/MARVEL/scripts/tour2fasta.py", line 468, in <module>
    main()
  File "/opt/MARVEL/scripts/tour2fasta.py", line 460, in main
    process_graph(g, db, dbc, fileSeq, paths, track_trim_name, seqname_prefix)
  File "/opt/MARVEL/scripts/tour2fasta.py", line 287, in process_graph
    (srid, dummy, dummy) = tsrc.get(i)
AttributeError: 'NoneType' object has no attribute 'get'

```

my networkx version 2.1

Do you have any idea for solving this error ? 
Thanks in advance !

**Comment by schloi** [comment]
Bunch of fixes just landed in the repository. Note that I updated the example do.py as well.

**Comment by sguizard** [comment]
You updated the code just in time ! I was able to run the e coli example and to run it on the data we were working on. So compare the MARVEL assembly to other assemblers and it insanly fast ! 
There were a lot of frameshift in the MARVEL assembly but i guess it can be improved by tweaking the parameters. 

Thank you very much for the tool and the quick code updating !

**Comment by schloi** [comment]
Just a note on the correction and frameshifts. The included correction was never intended to produce reference grade sequence. But it will get you to 99.x% identity quickly.

Depending on the assembly project we usually run the finishing tools from the respective long-read companies (here you will often end up with coverage requirements in excess of what was sequenced in the first place. as in the axolotl assembly) or map Illumina to get to the final sequence. 

There are a bunch of tools that take the final set of overlaps and produce sam/bam files containing mapping coordinates of the reads relative to the contigs in order to get around the mapping step of the long-read polishers. Those are not included in the git yet.

Given some spare time I will eventually revisit correction/polishing. But currently the Hi-C assembly tools take precedence.

**Comment by sguizard** [comment]
Thanks for these additionnals information. 
I was not expecting for the perfect assembly, and I think that perfection do not exists in assembly. Even the human and mousse are corrected each years. 
With a tool as fast and efficient as MARVEL, I cannot complain to do a polishing step to finalize the assembly. :)

I will take advantage of this comment to ask you a supplementary question, feel free to do not answer if you think it is not the good place for such discussion. 
Actually I am working on a tetraploïd plant genome. I would like, at least, to improve our reference genome or if it's possible to build a new high quality one. Did you test MARVEL on such genomes ? Will it able to build an assembly and separate the diffents copies of each chromosomes ? 

Thanks again for yours answers

**Comment by schloi** [comment]
If there is enough sequence divergence between the copies and the divergent stretches are large enough to induce alternatives paths through the assembly graph then yes. You will get contigs that are tagged as alternatives paths inside another contig, ie. the bubbles in the assembly graph are dumped as separate contigs and tagged accordingly. I only did that with diploid genomes so far, but I don't see a reason why this shouldn't work with genomes having higher ploidy numbers as well.

One scenario that might need some coding is when you end up with stacked bubbles in the graph.

and yes, it would be better to move this discussion to mail in case you have further questions...
