### ISSUE TITLE
OGtour.py finishes with no output

### ISSUE THREAD

**Issue by claumer** [schloi/MARVEL#13]
Hello Siegfried,

I'm very excited to have a crack at using the MARVEL assembler on some nanopore genome data that I've generated from several microscopic metazoan phyla.

However, I seem to be running into a bug or two with the current version and "do.py" script, which I think I ought to report. I had to alter the DBprepare.py file beforehand as described in other issue reports, but after that it got going fine. I am running as a multithreaded (20 core) job on our compute cluster, submitting the "do.py" script through LSF.

It seems to run alright through the first round of dalign, but then stops for no discernable reason after it has generated the block \*.fixed.fasta read files. I then commented out all commands from the first dalign until q.single("!cat {db}.\*.fixed.fasta > {db}.fixed.fasta"), and it seems to pick back up alright. It then runs the scrubbing/masking/overlap graph generation etc all apparently quite successfully (judging by the files it's generating) all the way until q.single("{path_scripts}/OGtour.py -c {db} {db}.graphml"). However, then my job again stops, without giving anything to stdout/stderr. If I comment out all commands in do.py from the second q definition until the OGtour.py step, and then run as an interactive job, again, it just runs for a few seconds, and then prints nothing back to my shell.

However, if I dispense with the queue class and just run OGtour.py directly, I see the following:

[claumer@ebi6-002 Gdys]$ ../../MARVEL_install_190218/scripts/OGtour.py -c Gdys_FIX Gdys_FIX.graphml
loading graph Gdys_FIX.graphml
touring...
Traceback (most recent call last):
  File "../../MARVEL_install_190218/scripts/OGtour.py", line 1248, in <module>
    main()
  File "../../MARVEL_install_190218/scripts/OGtour.py", line 1201, in main
    (g, paths, bbdist) = process_graph(g, args.dropinversions, args.circular, args.lookahead, ilookahead)
  File "../../MARVEL_install_190218/scripts/OGtour.py", line 838, in process_graph
    vread_prop = { n : g.nodes[n]["read"] for n in g }
  File "../../MARVEL_install_190218/scripts/OGtour.py", line 838, in <dictcomp>
    vread_prop = { n : g.nodes[n]["read"] for n in g }
TypeError: 'method' object is not subscriptable

Can you imagine what the problem(s) might be? Could it be a problem with my data (the coverage is not immense but 10-20X should be sufficient to assemble *something* I imagine)? Or is this a real bug? Keen to hear your thoughts.

Regards,
Chris L

**Comment by sguizard** [comment]
Which version of networkx do you have installed ?

**Comment by claumer** [comment]
It is 1.11 -- is that too old? Do you recommend upgrading to 2.1?

**Comment by sguizard** [comment]
If you take a look to the closed issue number 8, you will see that the code have been updated for supporting the version 2.X of networkx. So an upgrade of module should resolve the problem.

**Comment by claumer** [comment]
Indeed -- upgrading, it looks like I can now run the e.coli_nanopore example to completion with the provided do.py. (Impressively quickly!) Perhaps worth mentioning the requirement for the right networkx version in the README?

Now to try with my own data...

**Comment by schloi** [comment]
I added a requirements section to the README and a version check for networkx 2.1+ to the build scripts.
