### ISSUE TITLE
confusing command in axolotl assembly: "TKcombine {db} frepeats repeats maskc maskr"

### ISSUE THREAD

**Issue by SchwarzEM** [schloi/MARVEL#18]
MARVEL includes a rough recipe for how to assemble the axolotl genome (or, any genome of roughly axolotl's complexity).  In MARVEL's source tree, the recipe is located at:

    MARVEL/examples/axolotl/README

Most of the line commands in this recipe seem reasonably intelligible.  However, there's one of them that is baffling me.  It is in the "scrubbing phase", and it reads:

    TKcombine {db} frepeats repeats maskc maskr

I see no evidence whatsoever that '{db}' is actually what one should write here; my best guess is that the correct text here would have been 'AXOLOTL_FIX'.

Can somebody who understands these incantations better than I do please confirm or deny that my guess is correct?  And, if it is incorrect, what *should* the text for '{db}' have been?

**Comment by schloi** [comment]
oops, yeah that should have be been AXOLOTL_FIX in the README. I took some of the command lines from my python driver script for the assembly and seems I forgot to replace the {db} placeholder with the actual value.

**Comment by SchwarzEM** [comment]
OK, glad I guessed correctly.  Thanks for the bugfix!
