### ISSUE TITLE
Links to hdf5 header broken after configure

### ISSUE THREAD

**Issue by RNieuwenhuis** [schloi/MARVEL#2]
Hello,

Trying to install MARVEL I encountered the issue where the configure file cannot find HDF5.
I solved this by running:

./configure CPPFLAGS="-I/usr/include/hdf5/serial -L/usr/lib/x86_64-linux-gnu/hdf5/serial" LDFLAGS=-L/usr/lib/x86_64-linux-gnu/hdf5/serial

This worked, but resulted in the make spitting out the following:

build/oflags.sh lib/oflags.h lib.python/marvel/oflags.py
build/version.sh
for dir in corrector dalign db lib.python scripts scrub touring utils msa patcher experimental; do \
	if [ -d ./$dir ]; then \
		make -C $dir all ; \
	fi	\
done
make[1]: Entering directory '/usr/local/bin/marvel/corrector'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/usr/local/bin/marvel/corrector'
make[1]: Entering directory '/usr/local/bin/marvel/dalign'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/usr/local/bin/marvel/dalign'
make[1]: Entering directory '/usr/local/bin/marvel/db'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/usr/local/bin/marvel/db'
make[1]: Entering directory '/usr/local/bin/marvel/lib.python'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/usr/local/bin/marvel/lib.python'
make[1]: Entering directory '/usr/local/bin/marvel/scripts'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/usr/local/bin/marvel/scripts'
make[1]: Entering directory '/usr/local/bin/marvel/scrub'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/usr/local/bin/marvel/scrub'
make[1]: Entering directory '/usr/local/bin/marvel/touring'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/usr/local/bin/marvel/touring'
make[1]: Entering directory '/usr/local/bin/marvel/utils'
gcc -g -O2 -Wunused-macros -Wall -Wextra -I../   -o H5dextract H5dextract.c H5dextractUtils.c ../lib/stats.c -lhdf5 -lm -lz
H5dextract.c:21:18: fatal error: hdf5.h: No such file or directory
compilation terminated.
In file included from H5dextractUtils.c:1:0:
H5dextractUtils.h:8:18: fatal error: hdf5.h: No such file or directory
compilation terminated.
Makefile:61: recipe for target 'H5dextract' failed
make[1]: *** [H5dextract] Error 1
make[1]: Leaving directory '/usr/local/bin/marvel/utils'
make[1]: Entering directory '/usr/local/bin/marvel/msa'
gcc -g -O2 -Wunused-macros -Wall -Wextra -I../ -o msa msa.c msa_main.c ../lib/utils.c ../lib/pass.c ../dalign/align.c ../db/DB.c ../db/QV.c -lpthread -lm -lz
make[1]: Leaving directory '/usr/local/bin/marvel/msa'

So it seems the links are broken. Now I did some investigating and I stumbled upon this issue thread that is quite similar: https://github.com/HomerReid/scuff-em/issues/91 
Difference is it relies on autogen.sh, but the problem is the same I guess. As you can see the issue is solved with a commit changing configure.ac
Maybe this can work out for MARVEL as well.

**Comment by schloi** [comment]
I changed the build process to rely on ax_lib_hdf5.m4 for properly detecting the hdf5 includes/libraries, which is significantly more flexible than what I built manually. Please update your copy of the git repo, run autoreconf and give it another go.

**Comment by RNieuwenhuis** [comment]
Good solution, thank you!
