### ISSUE TITLE
syntax error near unexpected token `networkx'

### ISSUE THREAD

**Issue by tiramisutes** [schloi/MARVEL#6]
Hello,
I have to install networkx via ``pip install networkx`` , but I still get follows error:
```
./configure: line 3411: syntax error near unexpected token `networkx'
./configure: line 3411: `AC_PYTHON_MODULE(networkx)'
```
This is my version information: 
```
$  autoreconf --version
autoreconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
$  python --version
Python 3.6.1 :: Continuum Analytics, Inc.
```

Any suggestion?
Thanks.

**Comment by schloi** [comment]
Remote debugging of build issue is a pain... 

I updated the configure.ac file so the external macros, like the AC_PYTHON_MODULE which seems to be the problem at your end, are included explicitly. Please pull the changes from the git and run autoreconf and configure again.

**Comment by tiramisutes** [comment]
Yes, Now it's working. 
Thanks!
