### ISSUE TITLE
HPCdaligner parameter <-D host:port>

### ISSUE THREAD

**Issue by tiramisutes** [schloi/MARVEL#7]
Hello,
I want to assemble my genome follow the <examples/axolotl/README> show scripts. 
In this ``HPCdaligner`` step, whether the ``-D`` parameter is needed to set, and how to set?
Thanks!

**Comment by schloi** [comment]
I added some bits and pieces of info into the README.md. Additionally there is a howto in the docs subdir.

In essence, you only want the -D if you have a gigantic repeat rich genome.

**Comment by tiramisutes** [comment]
If my genome is not a gigantic repeat-rich genome, then I don't need to set the ``-D`` parameter and run subsequent ``DMserver`` step?

**Comment by schloi** [comment]
Yes, exactly. The only purpose of the dynamic masking server is to cut down on the number of CPU/hours and amount of storage required to pull of the assembly run of large repeat-rich genomes.
