### ISSUE TITLE
DBprepare.py not running to completion

### ISSUE THREAD

**Issue by morgancolp** [schloi/MARVEL#9]
Hi, 

Thanks for developing this tool!

I'm eager to give it a try to do a nanopore assembly, but I'm having issues with the DBprepare.py step of the procedure. The job ends up getting killed immediately, giving the following error:

groups: cannot find name for group ID 65476
(null): Could not open database ACAS
[ERROR] Cannot open database ACAS
(null): Could not open database ACAS
failed to open database

Do you know what might be causing this?

Thanks,
Morgan Colp

**Comment by morgancolp** [comment]
This is the shell script I am using

#!/bin/bash
#$ -S /bin/bash
. /etc/profile
#$ -cwd
#$ -pe threaded 8

unset PYTHONPATH
source /scratch2/software/python-3.4-env/bin/activate

/scratch2/software/MARVEL/scripts/DBprepare.py ACAS Acas_merged_pc_fl.fasta

The reads file comes from two nanopore runs with different chemistries, each treated with Porechop, merged and treated with Filtlong, then converted from fastq to fasta by simply removing the two fastq specific lines from each read.

**Comment by schloi** [comment]
The first error message definitely comes from the OS complaining about messed up group ids. I assume after that error everything goes downhill and DBprepare is unable to do what it is supposed to. The script only does some basic setting up and preprocessing and is thereby not really that heavy on the CPU. Guess that is my way of suggesting that you should skip your cluster's queue and see what happens.

I will add some additional error handling (always lacking) and a verbose mode to make tracking down issues like yours easier when I get around to it.

**Comment by morgancolp** [comment]
Thanks for the reply!

I tried DBprepare.py without using the cluster's queue, and got the following messages:

converting fasta to db ( min read length 2000 )
non-numeric value ffb48c2ac2d3f2fdf4c50b6b166ff12804b77128
partitioning db ( blocksize 200 )
(null): Could not open database ACAS
[ERROR] Cannot open database ACAS
dusting db
(null): Could not open database ACAS
creating plan
failed to open database

Could there be an issue with the fasta headers? I think the "ffb48c2ac2d3f2fdf4c50b6b166ff12804b77128" is derived from the nanopore naming scheme.

Files created when I tried to run DBprepare this time were:
.ACAS.bps
ACAS.dalign.plan
ACAS.dbx 
.ACAS.idx
ACAS.merge.plan

**Comment by schloi** [comment]
Can you paste me the full fasta header of one read ? I assume there are a bunch of "key=value" type comments in there.

**Comment by morgancolp** [comment]
Sure,

>4c05edbe-9a17-46e3-b623-c44d66d6f4e6_37-2456 runid=ffb48c2ac2d3f2fdf4c50b6b166ff12804b77128 read=100 ch=1 start_time=2017-06-05T20:18:42Z

**Comment by schloi** [comment]
sorry for taking my time, but putting stuff into moving boxes is keeping me busy at the moment.

anyway, I can offer a workaround for your problem which will do until I have the time to implement a proper fix for the issue.

open DBprepare.py in an editor, locate
`cmd = os.path.join(root, "FA2db -c") + opts`
and change the line to
`cmd = os.path.join(root, "FA2db ") + opts`
note the space beteen FA2db and the quote.

**Comment by morgancolp** [comment]
No problem! I'll give that a try.

**Comment by morgancolp** [comment]
Is there a limit on the read length that can be used by DBprepare? I am now getting the message:

File Acas_merged_pc_fl.fasta, Line 10832: Fasta line is too long (> 204798 chars)

**Comment by schloi** [comment]
Seems you have file that is not compliant with the FASTA standard, which dictates that a line should not contain more than 120 characters. I updated the fasta parsing to allow for lines of arbitrary length.

**Comment by morgancolp** [comment]
Thanks! Everything seems to be working now, provided I still use the workaround you described a couple of days ago for the DBprepare.py script

**Comment by sguizard** [comment]
Hi, 

I am testing MARVEL on a small genome and I had similar error for running DBprepare.py
One of the error message said : 
"non numeric value '6_0'"

I found the header contain the key/pair value iid={aNumber}_{aNumber}
I removed the last number and the associated _ and program ran without problems. 

Best regards

**Comment by sguizard** [comment]
Ok, I am testing MARVEL at a workshop genome assembly. 
The pacbio fasta file (provided by the instructor) that a first use was corrected read and that must the reason I got the error.

The program work perfectly on uncorrected reads. 

Best regards.

**Comment by schloi** [comment]
I checked in a proper fix that obviates the workaround
